apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer-deploy
  namespace: volunteer-service
  labels:
    app: volunteer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volunteer-service
  template:
    metadata:
      labels:
        app: volunteer-service
    spec:
      containers:
        - name: volunteer-service
          image: 956092955950.dkr.ecr.us-east-1.amazonaws.com/tech5/volunteer-service:bce05af524a848194b6047e4dbd6447308c9a80f
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          envFrom:
            - configMapRef:
                name: volunteer-configmap
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              drop:
                - ALL
