apiVersion: v1
kind: ConfigMap
metadata:
  name: ngo-configmap
  namespace: ngo-service
  labels:
    app: ngo-service
data:
  PORT: "8081"
  OTEL_SERVICE_NAME: "ngo-service"
  DATABASE_URL: "postgres://Postgresadmin:SenhaForte123!@ngodb.ca8z93ilhwfx.us-east-1.rds.amazonaws.com:5432/ngodb"
