apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngo-deploy
  namespace: ngo-service
  labels:
    app: ngo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngo-service
  template:
    metadata:
      labels:
        app: ngo-service
    spec:
      containers:
        - name: ngo-service
          image: 956092955950.dkr.ecr.us-east-1.amazonaws.com/tech5/ngo-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          envFrom:
            - secretRef:
                name: ngo-secret
            - configMapRef:
                name: ngo-configmap
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
