apiVersion: v1
kind: Secret
metadata:
  name: ngo-secret
  namespace: ngo-service
type: Opaque
stringData:
  DATABASE_URL: "postgres://Postgresadmin:SenhaForte123!@ngodb.ca8z93ilhwfx.us-east-1.rds.amazonaws.com:5432/ngo_db"
