deploymentMode: SingleBinary

loki:
  auth_enabled: false
  limits_config:
    volume_enabled: true
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

singleBinary:
  replicas: 1

  persistence:
    enabled: true
    storageClass: local-path
    size: 20Gi
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

chunksCache:
  enabled: false

resultsCache:
  enabled: false

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

chunksCache:
  enabled: false

resultsCache:
  enabled: false