apiVersion: v1
kind: ConfigMap
metadata:
  name: donation-configmap
  namespace: donation-service
  labels:
    app: donation-service
data:
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/000000000000/CHANGE_ME"
