apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: donation-hpa
  namespace: donation-service
spec:
  scaleTargetRef: # O recurso que o HPA vai escalar
    apiVersion: apps/v1
    kind: Deployment
    name: donation-deploy
  minReplicas: 1  # Mínimo de pods
  maxReplicas: 3 # Máximo de pods
  metrics:        # Critérios para escalonamento
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Escala se a CPU média passar de 50%