apiVersion: v1
kind: Secret
metadata:
  name: donation-secret
  namespace: donation-service
type: Opaque
stringData:
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ASIA55G4UXUXCGAJ7BIB
  AWS_SECRET_ACCESS_KEY: TjRYSTZUWXdxb0VvcHNuYzNuMmFjekQ5YTFwSGtGRGkza1F3eVMzOQ==
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjECoaCXVzLXdlc3QtMiJGMEQCIHxrnac1m+tBCFvHMKeue7zLjGAAt1IMbbkqIvHDhfzHAiBja4cWeTJZ3k9pDY8/hEfPyT1etFCIuKJS8Oye2M5HBiq9Agjz//////////8BEAEaDDk1NjA5Mjk1NTk1MCIM64SUX1Ofsj2xUNN0KpECoFUv9RVpnk6iKCkN2wQF3Q7ErvpehEdKHvfB99Frb34ozrbaLNKzSFyWsGTOqrgDgMqdRDg8mf+eS0KHNEq9WJMjmpJxrHo6Y7J+lAmCjFmRLEW65h+pLPnbEY092ID75GhSuv5StvI+PHDyPZXxg6o5bKMFQJBmJS8EhvPSACPuQnNROiJ4dgczG1YEDpjyaXEHUtN+eadA0sAbOcVdH6Bh1R3ebdHBO64GdtIcqEzXhJOx2I6+DVUm6DBLdeaUefNuTHYCyhaexg1zrOsNY8BsPrg796ABU3U3Yao7I6mNMd9UmoAJjiSt+N6Ij6YOZN4647g0Z4pae99Q9Dp8TCP8swhGLLlnLM11eyDO2CPmMJiAstQGOp4BdAcM8tirbLTPUuyYmRJQWcLxJvnxroDwOYtoPq1YDPMswirol4sImHBOWs9T9N2xoF1zpGAOuWNMrb7cGc65zLuhktRvqTbT0t/VhHPdOmQpeesrZJrNl/afXHw/2ckUUjzLCTdFZy++iUMjFhMdc01FwVh9Jzjpz+bkXcd1FVIUTlLbjHPWGx70B46ZcRHE43jH1A/12p19jGU/hyE=