apiVersion: v1
kind: Secret
metadata:
  name: donation-secret
  namespace: donation-service
type: Opaque
stringData:
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: QVNJQTU1RzRVWFVYRVJIS0FLQ1I=
  AWS_SECRET_ACCESS_KEY: SkIyb2dpMXYvS1hBVnJHTjQ0QVBhaHJPdTU3MmFSVXltU2lqWGZnLw==
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEAMaCXVzLXdlc3QtMiJGMEQCIETDDuFKozTzE+w556YHYQasZClWZTOrFytjCeSYrjseAiAWgKrslzziTFKQYL3pQC6vqkbfrLIv8EH0u2xzRTZMbCq9AgjM//////////8BEAEaDDk1NjA5Mjk1NTk1MCIM8qk9NMQqUauyRMx6KpECt3D7BKXLB9hynhWen3OZLZ1/i6GsjiPaj4aOImrnQWkSvG9zfZ4foPYa3Dv4PqfAhhu6pJwo9hAhlKydNc6y2dyU2WQuMRudCbuLWKfYrNqQZisVCGP5jQrBSV60JUvnHxgW2RuviZDjNJDBC2G8P4stdpvF6/Pf999mY+7w+WYP0CWt2G4wLo+y6xKaUlytiskW1Yhbo2PKVcWxKbwlgEqdXBDOuY44g/3WPt87Q6yrkNCX6PgH+L8deDapzQxZNznCS+NixyRr0qWUZ8bpemDrOTFWs8KMwUyVdWuCE76ngY97ri+Pgsdm+VPxqt1mVcMgfvyvmB1LMqRXtan1w3qXu4IQCID7Lbo0ydskOQc2MO3k4dQGOp4BwxabI2LRn3+MxOTRbj8xxIL2xogIsJDsoxbxemgCJiIL//NyLsoRGMDe8h+e+kaMPCrZhmvmM9srr0tKSGJ2ygOdqq02wsn2ZGTskHyoqAAa6tRGc2z0jWDngM0Q0AfXU15rOxYwiAEt/R64uv47lfc2UmHwsRZwDqhUohkGG3xYIKkgn61WEvmr8KoQklowCwIpsAgsgwAsvxCRLlo=