apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: donation-service
  namespace: donation-service
spec:
  selector:
    matchLabels:
      app: donation-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      honorLabels: true