name: AWS Deploy
on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Configura a AWS no Job atual (usando as secrets do repositório)
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # 2. Faz o login no Amazon ECR
      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Faz o build e push do serviço que foi passado como parâmetro
      - name: Build and Push to ECR
        id: build-push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: tech5/${{ inputs.service_name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Fazendo build do microsserviço: ${{ inputs.service_name }}"

          # Garante que o repositório ECR existe na AWS (cria se não existir)
          aws ecr describe-repositories --repository-names $REPOSITORY --region us-east-1 || aws ecr create-repository --repository-name $REPOSITORY --region us-east-1

          cd app/${{ inputs.service_name }}

          # Build e Tag
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest

          # Push
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Update GitOps Repo
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: tech5/${{ inputs.service_name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          git clone https://${{ secrets.GITOPS_PAT }}@github.com/PosFiap-DCTL2/tech-challenge-5
          cd tech-challenge-5/Kubernetes/${{ inputs.service_name }}

          sed -i "s|^\(\s*image:\s*\).*${{ inputs.service_name }}:.*|\1$REGISTRY/$REPOSITORY:$IMAGE_TAG|" deployment.yaml

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "feat(${{ inputs.service_name }}): Update da imagem para $IMAGE_TAG"
          git push
