name: AWS Deploy
on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 1. Configura a AWS no Job atual (usando as secrets do repositório)
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          
      # 2. Faz o login no Amazon ECR
      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Faz o build e push do serviço que foi passado como parâmetro
      - name: Build and Push to ECR

        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: tech5/${{ inputs.service_name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Fazendo build do microsserviço: ${{ inputs.service_name }}"
          
          FULL_IMAGE_NAME="$REGISTRY/$REPOSITORY:$IMAGE_TAG"
          
          cd app/${{ inputs.service_name }}
          
          # Build
          docker build -t $FULL_IMAGE_NAME .
          
          # Push
          docker push $FULL_IMAGE_NAME
